# -*- coding: utf-8 -*-
"""resnet50_image1k_pretraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEN6NFBB6Jkmj769DXnFtm6k_lHF1krf
"""

import timm

def resnet50_pre_image1k(pretrained = True, num_classes = 6):
  model_res50_pre_in1k = timm.create_model('resnet50', pretrained=pretrained, num_classes=num_classes)
  return model_res50_pre_in1k