# -*- coding: utf-8 -*-
"""resnet50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_zVPA1UxVJOXCsza2BUeoAorrNIsWE1
"""

import numpy as np
import torch
import torch.nn as nn
import torchvision

def resnet50(pretrained = False, num_classes = 6):
  model_res_nonpre = torchvision.models.resnet50(pretrained=False)
  model_res_nonpre.fc = nn.Linear(model_res_nonpre.fc.in_features, num_classes)
  return model_res_nonpre

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)