# -*- coding: utf-8 -*-
"""vit_image1k_pretraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwZM8ZZ_lW1Yv0ViWPB-xseILQQWL5gz
"""

import timm

def vit_pre_image1k(pretrained = True, num_classes = 6):
  model_vit_pre_in1k = timm.create_model('vit_base_patch16_224', pretrained=pretrained, num_classes=num_classes)
  return model_vit_pre_in1k