# -*- coding: utf-8 -*-
"""vit_image21k_pretraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HwC9YTxVercTcs9Z0ww3411QT26L8JCf
"""

import timm

def vit_pre_image21k(pretrained = True, num_classes = 6):
  model_vit_pre_in21k = timm.create_model('vit_base_patch16_224_miil_in21k', pretrained=pretrained, num_classes=num_classes)
  return model_vit_pre_in21k