# -*- coding: utf-8 -*-
"""loader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_zVPA1UxVJOXCsza2BUeoAorrNIsWE1
"""

import numpy as np
import torch
from torchvision.transforms import transforms
from torchvision.datasets import ImageFolder

def loaddata(train_dir, test_dir, batchsize=32):
  train_data_dir  = train_dir
  data_norm_mean = [0.4294, 0.4578, 0.4563]
  data_norm_std = [0.2600, 0.2594, 0.2921]
  transformationtrain = transforms.Compose([
    transforms.Resize((280,280)),
    transforms.RandomResizedCrop(224, scale=(0.64, 1.0), ratio=(1.0, 1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=data_norm_mean, std=data_norm_std)
    ])
  train_data = ImageFolder(train_data_dir, transform = transformationtrain)
  val_data_dir  = test_dir
  transformationtest = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=data_norm_mean, std=data_norm_std)
    ])
  val_data = ImageFolder(val_data_dir, transform = transformationtest)
  # val_data, test_data = random_split(val_data, [1500, 1500])
  trainDataLoader = torch.utils.data.DataLoader(train_data,batch_size=batchsize,shuffle=True)
  valDataLoader = torch.utils.data.DataLoader(val_data,batch_size=batchsize,shuffle=False)
  testDataLoader = torch.utils.data.DataLoader(val_data,batch_size=batchsize,shuffle=False)
  return trainDataLoader, valDataLoader, testDataLoader